### ISSUE TITLE
Pattern match failure on start in case of unbalanced transactions

### ISSUE THREAD

**Issue by t-wissmann** [hpdeifel/hledger-iadd#1]
In case of an unbalanced transaction, `hledger-iadd` refuses to start with the message:
```
hledger-iadd: user error (Pattern match failure in do expression at src/Main.hs:281:3-15)
```
A minimal `~/.hledger.journal` triggering this is the following and was written using hledger-iadd:
```
2016/08/20 unbalanced
    Cash             1

```

**Comment by t-wissmann** [comment]
That happend with an old git version, sorry for that! Since 966b3706d075233841dc90f6314ccaf85c5e7509, there is a meaningful error message instead:
```
could not balance this transaction (real postings are off by 1)
2016/08/20 unbalanced
    Cash             1

```
However, hledger-iadd does not start up, even though the journal file was generated by hledger-iadd itself. So I suggest to either ignore this kind of 'unbalanced' errors or not to allow saving unbalanced transactions to the journal.

**Comment by hpdeifel** [comment]
> However, hledger-iadd does not start up, even though the journal file
> was generated by hledger-iadd itself. So I suggest to either ignore
> this kind of 'unbalanced' errors or not to allow saving unbalanced
> transactions to the journal.

It does warn you when you try to add an unbalanced transaction.

The problem is that the function I use for parsing the journal
`parseAndFinaliseJournal` returns an error if a transaction is
unbalanced and doesn't give me the journal data. So apart from the
current behaviour of not starting, I see two alternatives:

1. Warn and start up without having the journal data. Everything would
   work fine except you won't have any completions.
2. Work around parseAndFinaliseJournal using the other combinators from
   Hledger.Read.Journal to try to parse the journal anyway. (I'm not
   exactly sure what the "finalize" step of parseAndFinaliseJournal is
   supposed to do, but it probably does the balance checking)

What do you prefer?

**Comment by t-wissmann** [comment]
First I prefered 2, but after a some reading I prefer changing that warning to an error-message.

The strange thing is that neither of the hledger tools can handle an unbalanced transaction in the journal. I get the same error message when running `add`, `bal`, `ui`.

That's probably because they all depend on `balanceTransaction` of `Hledger/Data/Transaction.hs` (it's called by  `journalFinalise` in `Hledger/Data/Journal.hs` which is again called in the finalising step of `parseAndFinaliseJournal`.)

So wrt "1 vs 2" I vote for: do the same thing as `add`, `ui`, etc by sticking to parseAndFinaliseJournal and let them find a common solution. But for the time being, I'd disallow adding unbalanced times.

I also don't see a point in a warning message of the kind "Do you really want to add this unbalanced transaction to the journal? If you do so, no hledger tool out there will be able to work with your journal anymore"

The reason why I overlooked the warning was because there's always a confirmation question looking nearly the same (with the default answer <kbd>y</kbd>) before the transaction is written to the journal.

**Comment by simonmichael** [comment]
Currently all of hledger is designed to require a valid journal before doing anything else. Do you think that policy is wrong ?

And there is some inconsistency. The balanced transaction check can not be disabled, but balance assertions can. In future there will be more kinds of validation, so there should be some consistent policy.

**Comment by simonmichael** [comment]
PS so what I would tend to do here is give an error right away if the journal is invalid. We expect the user to fix it, which is not too bad since presumably they presumably caused it. (A nice feature would be a doctor which offers to repair things for you.)

**Comment by hpdeifel** [comment]
@t-wissmann I agree with that and will disallow adding unbalanced transactions.

@simonmichael Thanks for the context! The policy is absolutely fine for all reporting tools. It's a little more debatable for `add`/`iadd`, since they don't strictly require a valid journal. But nevertheless: I think it's good to consistently tell the user early and loudly that her journal requires fixing. So I'll keep the current behaviour of throwing an error if the journal is invalid.
