### ISSUE TITLE
Released binary fails on `Cash` account code

### ISSUE THREAD

**Issue by metiulekm** [hpdeifel/hledger-iadd#51]
Consider the following journal contents:

```
account A  ; type: Cash
account B  ; type: Expense

2021-01-29 asd
    A             1 X
    B            -1 X
```

`hledger 1.20.4` works correctly:

```
> hledger bal -f ~/test.journal
                 1 X  A
                -1 X  B
--------------------
                   0
```

However, the binary from <https://github.com/hpdeifel/hledger-iadd/releases/download/v1.3.12/hledger-iadd-1.3.12-archlinux.tar.xz> fails with:

```
/home/metiulekm/test.journal:1:1:
  |
1 | account A  ; type: Cash
  | ^
invalid account type code Cash, should be one of A, L, E, R, X, ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE
```

Maybe it's compiled against old `hledger-lib`?

**Comment by hpdeifel** [comment]
You are right. The last release is from august and this feature was introduced in September in hledger-lib.

I usually only release new versions of `iadd` if the existing release doesn't build against newer `hledger-lib` versions any more. Also, I only rebuild the arch-binary for new releases.

Can you build from source? Otherwise, I could make a new binary tomorrow.

**Comment by metiulekm** [comment]
I can build from source, the only reason for me not to is my laziness :) I use the AUR package (checked against release tarball to be 100% sure), but I probably could write some PKGBUILD that does the right thing.

Feel free to close if you want.

**Comment by hpdeifel** [comment]
Ok, new release is out and links against a newer hledger-lib!
